{{- if .Values.python.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  #name: {{ include "microservices.serviceAccountName" . }}
  name: {{ .Values.python.serviceAccount.name }}
  labels:
    {{- include "microservices.pythonLabels" . | nindent 4 }}
  {{- with .Values.python.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.python.serviceAccount.automount }}
{{- end }}
