apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}-{{ .Values.react.name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  {{- if not .Values.react.autoscaling.enabled }}
  replicas: {{ .Values.react.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservices.reactLabel" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.react.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "microservices.reactLabel" . | nindent 8 }}
        {{- with .Values.react.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.react.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.react.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.react.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{.Values.react.name}}
          securityContext:
            {{- toYaml .Values.react.securityContext | nindent 12 }}
          image: "{{ .Values.react.image.repository }}:{{ .Values.react.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.react.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.react.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.react.resources | nindent 12 }}
          {{- with .Values.react.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.react.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.react.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.react.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.react.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
