{{- if .Values.react.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  #name: {{ include "microservices.serviceAccountName" . }}
  name: {{ .Values.react.serviceAccount.name }}
  labels:
    {{- include "microservices.reactLabels" . | nindent 4 }}
  {{- with .Values.react.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.react.serviceAccount.automount }}
{{- end }}
