apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-{{ .Values.react.name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.react.service.type }}
  ports:
    - port: {{ .Values.react.service.port }}
      targetPort: {{ .Values.react.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "microservices.reactLabel" . | nindent 4 }}
