#python
python:
  name: python
  replicaCount: 1
  image:
    repository: devopskarthik123/python-kub
    pullPolicy: IfNotPresent
    tag: "v02"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: false
    automount: true
    annotations: {}
    name: "python-service"

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 3000
    targetport: 3000

  ingress:
    enabled: false 
    className: "nginx"
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: devopslearning.live
        paths:
          - path: /
            pathType: Prefix
    tls: 
      - secretName: ingress-testing 
        hosts:
          - devopslearning.live

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

#react
react:
  name: react
  replicaCount: 1
  image:
    repository: devopskarthik123/react
    pullPolicy: IfNotPresent
    tag: "react"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: false
    automount: true
    annotations: {}
    name: "react-service"

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 3000
    targetport: 3000

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: devopslearning.live
        paths:
          - path: /
            pathType: Prefix
    tls: 
      - secretName: ingress-testing 
        hosts:
          - devopslearning.live

  resources: 
     limits:
       cpu: 1
       memory: 1Gi
     requests:
       cpu: 500m
       memory: 500Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}
